BRE-40 ADD action.yml file for reporting upcoming release version to Slack
bitwarden/gh-actions pull request #281
Opened 2024-05-15 23:25 UTC by urbinaalex17

## 🎟️ Tracking

Jira: https://bitwarden.atlassian.net/browse/BRE-40 
Notify #release with version for upcoming release

## 🚧 Type of change

-   🚀 New feature development

## 📔 Objective

To help enable better communication and visibility, and to align the entire company expectations, we would like to send a slack notification to #release with the projects and their corresponding version bumps.

## 📋 Code changes

-   Add **report-upcoming-release-version/action.yml:** Initial GitHub Action.

## 📸 Screenshots

## ⏰ Reminders before review

-   Contributor guidelines followed
-   All formatters and local linters executed and passed
-   Written new unit and / or integration tests where applicable
-   Used internationalization (i18n) for all UI strings
-   CI builds passed
-   Communicated to DevOps any deployment requirements
-   Updated any necessary documentation or informed the documentation team

## 🦮 Reviewer guidelines

-   👍 (`:+1:`) or similar for great changes
-   📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
-   ❓ (`:question:`) for questions
-   🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
-   🎨 (`:art:`) for suggestions / improvements
-   ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
-   🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
-   ⛏ (`:pick:`) for minor or nitpick changes

2024-05-16 16:46 UTC, mimartin12 requested changes
Various changes around consistency and grammar.

I would also like to see some tests for this, similar to how we are doing it with `report-deployment-status-to-slack` action. Can you include those in this PR so that we can have tests runs on this prior to changes?

2024-05-16 16:46 UTC, mimartin12 commented on report-upcoming-release-version/action.yml
> +    value: ${{ steps.slack-message.outputs.channel_id }}
⛏️  Grammar change
```suggestion
    description: "Channel ID where the Slack message was posted."
    value: ${{ steps.slack-message.outputs.channel_id }}
```

2024-05-16 16:46 UTC, mimartin12 commented on report-upcoming-release-version/action.yml
> +    - name: Login to Azure - Prod Subscription
❓ Can we always assume the type of subscription here?
`name: Login to Azure - Prod Subscription`

Maybe something like this wouldn't assume details that may not be correct.
```suggestion
    - name: Login to Azure
```

2024-05-16 16:46 UTC, mimartin12 commented on report-upcoming-release-version/action.yml
> +        echo 'EOF' >> $GITHUB_OUTPUT
⛏️  Consistency recommendations.
```suggestion
        echo "slack_message<<EOF" >> $GITHUB_OUTPUT
        echo "$SLACK_MESSAGE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
```

2024-05-16 20:42 UTC, mimartin12 requested changes
The changes look good, thanks @alex8bitw!

However, we are still missing tests. A simple add would be similar to this. https://github.com/bitwarden/gh-actions/blob/main/.github/workflows/test-report-deployment-status-to-slack.yml. These should run when you make changes to the composite action, can you please add them to this PR?

2024-05-21 00:22 UTC, urbinaalex17 commented
> The changes look good, thanks @urbinaalex17 !
> 
> However, we are still missing tests. A simple add would be similar to this. https://github.com/bitwarden/gh-actions/blob/main/.github/workflows/test-report-deployment-status-to-slack.yml. These should run when you make changes to the composite action, can you please add them to this PR?

This PR is ready to be merged! Thanks for the suggestions, @mimartin12!

2024-05-21 16:47 UTC, merged